# Ones and Zeroes

In [1]:
import numpy as np
x=np.empty([3,3], np.int8)
print(x)

[[ 84   0 121]
 [  0 112   0]
 [101   0   0]]


In [4]:
y=np.eye(3,dtype=np.uint8)
print(y)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
y=np.eye(3,dtype=np.uint8,k=2)
print(y)

[[0 0 1]
 [0 0 0]
 [0 0 0]]


In [6]:
y=np.eye(3,dtype=np.uint8,k=-1)
print(y)

[[0 0 0]
 [1 0 0]
 [0 1 0]]


In [7]:
x=np.ones((3,5,5),dtype=np.int16)
print(x)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [10]:
x=np.zeros((2,5,5),dtype=np.int16)
print(x)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [11]:
x=np.ones((3,3,3),dtype=np.int16)
print(x)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [13]:
x=np.full((3,3,3),dtype=np.int16,fill_value=7)
print(x)

[[[7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]]]


# Matrix Creation Routines

In [16]:
x=np.tri(5,5,k=0,dtype=np.uint16)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [17]:
x=np.tri(5,5,k=-1,dtype=np.uint16)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [18]:
x=np.tri(5,5,k=1,dtype=np.uint16)
print(x)

[[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [21]:
x=np.ones((5,5),dtype=np.uint16)
y=np.tril(x,k=0)
print(y)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


In [22]:
x=np.ones((5,5),dtype=np.uint16)
y=np.triu(x,k=0)
print(y)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


In [23]:
x=np.ones((5,5),dtype=np.uint16)
y=np.tril(x,k=-1)
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [24]:
x=np.ones((5,5),dtype=np.uint16)
y=np.tril(x,k=1)
print(y)

[[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]
