# Array Manipulation Routines

In [1]:
import numpy as np
x=np.arange(6)
print(x)

[0 1 2 3 4 5]


In [2]:
y=x.reshape((3,2))
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [6]:
x=np.array([[0,1,2],[3,4,5]], dtype=np.uint16)
print(x)

[[0 1 2]
 [3 4 5]]


In [7]:
y=np.reshape(x,6)
print(y)

[0 1 2 3 4 5]


In [8]:
y=np.ravel(x)
print(y)

[0 1 2 3 4 5]


In [9]:
y=x.flatten()
print(y)


[0 1 2 3 4 5]


In [10]:
y=x.flatten('F')
print(y)

[0 3 1 4 2 5]


In [11]:
x=np.array([1,2,3],dtype=np.uint8)
y=np.array([4,5,6],dtype=np.uint8)
print(x)
print(y)

[1 2 3]
[4 5 6]


In [13]:
z=np.stack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [14]:
z=np.stack((x,y),axis=1)
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [15]:
z=np.dstack((x,y))
print(z)

[[[1 4]
  [2 5]
  [3 6]]]


In [16]:
z=np.hstack((x,y))
print(z)

[1 2 3 4 5 6]


In [17]:
z=np.vstack((x,y))
print(z)

[[1 2 3]
 [4 5 6]]


In [18]:
x=np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [19]:
a,b,c=np.split(x,3)
print(a,b,c)

[0 1 2] [3 4 5] [6 7 8]


In [20]:
x=np.random.rand(4,4,4)
print(x)


[[[0.70677659 0.42091947 0.93285231 0.64677939]
  [0.72010314 0.19561882 0.54713446 0.00400951]
  [0.86852084 0.77558755 0.9959031  0.65581772]
  [0.56263494 0.1651634  0.85541449 0.06017919]]

 [[0.53509024 0.58531569 0.16255829 0.81939531]
  [0.29156671 0.52171526 0.89634497 0.97712933]
  [0.75285917 0.39078728 0.86246041 0.0841666 ]
  [0.77962027 0.37180703 0.19771131 0.10962463]]

 [[0.37303412 0.22012414 0.82425801 0.91339615]
  [0.1033415  0.97834049 0.44235436 0.17982419]
  [0.9429355  0.39028336 0.28809054 0.52793684]
  [0.5855723  0.23941258 0.7120363  0.18235688]]

 [[0.89519115 0.83425971 0.60291779 0.98815133]
  [0.93183175 0.82285531 0.78310148 0.40653092]
  [0.22253533 0.52901376 0.23212686 0.12669882]
  [0.37716616 0.26556222 0.16780255 0.36853442]]]


In [21]:
y,z=np.split(x,2)
print(y)

[[[0.70677659 0.42091947 0.93285231 0.64677939]
  [0.72010314 0.19561882 0.54713446 0.00400951]
  [0.86852084 0.77558755 0.9959031  0.65581772]
  [0.56263494 0.1651634  0.85541449 0.06017919]]

 [[0.53509024 0.58531569 0.16255829 0.81939531]
  [0.29156671 0.52171526 0.89634497 0.97712933]
  [0.75285917 0.39078728 0.86246041 0.0841666 ]
  [0.77962027 0.37180703 0.19771131 0.10962463]]]


In [22]:
y,z=np.dsplit(x,2)
print(y)

[[[0.70677659 0.42091947]
  [0.72010314 0.19561882]
  [0.86852084 0.77558755]
  [0.56263494 0.1651634 ]]

 [[0.53509024 0.58531569]
  [0.29156671 0.52171526]
  [0.75285917 0.39078728]
  [0.77962027 0.37180703]]

 [[0.37303412 0.22012414]
  [0.1033415  0.97834049]
  [0.9429355  0.39028336]
  [0.5855723  0.23941258]]

 [[0.89519115 0.83425971]
  [0.93183175 0.82285531]
  [0.22253533 0.52901376]
  [0.37716616 0.26556222]]]


In [23]:
y,z=np.hsplit(x,2)
print(y)

[[[0.70677659 0.42091947 0.93285231 0.64677939]
  [0.72010314 0.19561882 0.54713446 0.00400951]]

 [[0.53509024 0.58531569 0.16255829 0.81939531]
  [0.29156671 0.52171526 0.89634497 0.97712933]]

 [[0.37303412 0.22012414 0.82425801 0.91339615]
  [0.1033415  0.97834049 0.44235436 0.17982419]]

 [[0.89519115 0.83425971 0.60291779 0.98815133]
  [0.93183175 0.82285531 0.78310148 0.40653092]]]


In [24]:
y,z=np.vsplit(x,2)
print(y)

[[[0.70677659 0.42091947 0.93285231 0.64677939]
  [0.72010314 0.19561882 0.54713446 0.00400951]
  [0.86852084 0.77558755 0.9959031  0.65581772]
  [0.56263494 0.1651634  0.85541449 0.06017919]]

 [[0.53509024 0.58531569 0.16255829 0.81939531]
  [0.29156671 0.52171526 0.89634497 0.97712933]
  [0.75285917 0.39078728 0.86246041 0.0841666 ]
  [0.77962027 0.37180703 0.19771131 0.10962463]]]


In [25]:
x=np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [26]:
y=np.flip(x,axis=-1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [27]:
y=np.flip(x,axis=0)
print(y)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [28]:
y=np.flip(x,axis=1)
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [30]:
y=np.fliplr(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [31]:
y=np.flipud(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [33]:
y=np.roll(x,8)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [34]:
y=np.rot90(x)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
