# Dot Product

In [2]:
import numpy as np
print(np.dot(10,5))

50


In [5]:
a=np.array([2,4],np.uint8)
b=np.array([5,6],np.uint8)
print(np.dot(a,b))

34


In [6]:
a=np.array([[2,4],[5,8]],np.uint8)
b=np.array([[5,6],[9,3]],np.uint8)
print(np.dot(a,b))

[[46 24]
 [97 54]]


# Vector Dot Product

In [7]:
a=np.array([1,2])
b=np.array([3,4])
print(np.vdot(a,b))

11


In [9]:
a=np.array([1+5j,2+3j])
b=np.array([3+7j,4+2j])
print(np.vdot(a,b))
print(np.vdot(b,a))

(52-16j)
(52+16j)


# Inner Product

In [10]:
a=np.array([1,2,3,4,5,6])
b=np.array([0,1,0,1,0,1])
print(np.inner(a,b))

12


In [11]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[0,1,0],[1,0,1]])
print(np.inner(a,b))

[[ 2  4]
 [ 5 10]]


# QR Decomposition

In [12]:
a=np.random.rand(3,3)
print(a)

[[0.24869226 0.93387471 0.20125107]
 [0.2165432  0.83464311 0.9192979 ]
 [0.03614938 0.86361925 0.78420099]]


In [13]:
q,r=np.linalg.qr(a)
print('q=',q,'\n\n r=',r,'\n')
print(np.dot(q,r))

q= [[-0.74968009 -0.09690171 -0.65466772]
 [-0.6527671  -0.05461425  0.75558745]
 [-0.1089719   0.99379442 -0.02231103]] 

 r= [[-0.33173118 -1.33904507 -0.83641722]
 [ 0.          0.72218252  0.70962622]
 [ 0.          0.          0.54536104]] 

[[0.24869226 0.93387471 0.20125107]
 [0.2165432  0.83464311 0.9192979 ]
 [0.03614938 0.86361925 0.78420099]]


# Determinant and Solving Linear Equations

In [15]:
a=np.array([[5,6],[3,4]])
print(np.linalg.det(a))

1.9999999999999971


In [16]:
a=np.array([[2,1,-3],[4,2,-1],[3,5,-2]],np.int16)
b=np.array([-4,9,5],np.int16)
x=np.linalg.solve(a,b)
print(x)

[2.74285714 0.71428571 3.4       ]
